"""new fields for sensor's data

Revision ID: 2262aaf397dd
Revises: d6a14d2355b3
Create Date: 2026-04-21 11:07:07.847308

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2262aaf397dd'
down_revision = 'd6a14d2355b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mediciones_sensor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temperatura_suelo', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('humedad_suelo', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('temperatura_minima', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('temperatura_maxima', sa.Float(), nullable=True))
        batch_op.alter_column('humedad_foliar',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('temperatura_DS18B20',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('temperatura_hojas',
               existing_type=mysql.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mediciones_sensor', schema=None) as batch_op:
        batch_op.alter_column('temperatura_hojas',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('temperatura_DS18B20',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('humedad_foliar',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.drop_column('temperatura_maxima')
        batch_op.drop_column('temperatura_minima')
        batch_op.drop_column('humedad_suelo')
        batch_op.drop_column('temperatura_suelo')

    # ### end Alembic commands ###
