"""modified logica de recursos

Revision ID: 237f001c7e87
Revises: 1532f2ca547c
Create Date: 2026-04-10 12:32:03.307852

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '237f001c7e87'
down_revision = '1532f2ca547c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metadatos', schema=None) as batch_op:
        batch_op.alter_column('valor',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Text(),
               nullable=False)
        batch_op.alter_column('fuente',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('fecha_creacion',
               existing_type=mysql.DATETIME(),
               nullable=True)

    with op.batch_alter_table('plagas', schema=None) as batch_op:
        batch_op.alter_column('public_id',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('agente_causante',
               existing_type=mysql.VARCHAR(length=300),
               type_=sa.String(length=100),
               nullable=False)

    with op.batch_alter_table('predicciones', schema=None) as batch_op:
        batch_op.alter_column('tendencia_temp_max',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('tendencia_temp_min',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)

    with op.batch_alter_table('tipo_dato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tipo_dato', schema=None) as batch_op:
        batch_op.drop_column('descripcion')

    with op.batch_alter_table('predicciones', schema=None) as batch_op:
        batch_op.alter_column('tendencia_temp_min',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('tendencia_temp_max',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('plagas', schema=None) as batch_op:
        batch_op.alter_column('agente_causante',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=300),
               nullable=True)
        batch_op.alter_column('public_id',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)

    with op.batch_alter_table('metadatos', schema=None) as batch_op:
        batch_op.alter_column('fecha_creacion',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('fuente',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('valor',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
