"""estado inicial

Revision ID: 42a341b60114
Revises: 
Create Date: 2026-04-04 18:41:00.190058

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '42a341b60114'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cultivos', schema=None) as batch_op:
        batch_op.alter_column('grupo',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.create_foreign_key(None, 'sensores', ['sensor_id'], ['id'])

    with op.batch_alter_table('metadatos', schema=None) as batch_op:
        batch_op.alter_column('clave',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('valor',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('fuente',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('fecha_creacion',
               existing_type=mysql.DATETIME(),
               nullable=True)

    with op.batch_alter_table('plagas', schema=None) as batch_op:
        batch_op.alter_column('public_id',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('agente_causante',
               existing_type=mysql.VARCHAR(length=300),
               type_=sa.String(length=100),
               nullable=False)

    with op.batch_alter_table('predicciones', schema=None) as batch_op:
        batch_op.alter_column('tendencia_temp_max',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('tendencia_temp_min',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predicciones', schema=None) as batch_op:
        batch_op.alter_column('tendencia_temp_min',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('tendencia_temp_max',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('plagas', schema=None) as batch_op:
        batch_op.alter_column('agente_causante',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=300),
               nullable=True)
        batch_op.alter_column('public_id',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)

    with op.batch_alter_table('metadatos', schema=None) as batch_op:
        batch_op.alter_column('fecha_creacion',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('fuente',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('valor',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('clave',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('cultivos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('grupo',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
