"""add logica de recursos necesarios para plagas

Revision ID: 5ac32664c4c2
Revises: b8db2f278ff7
Create Date: 2026-04-10 11:40:46.724257

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5ac32664c4c2'
down_revision = 'b8db2f278ff7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipo_dato',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('cultivo_plaga_requisito',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cultivo_plaga_id', sa.Integer(), nullable=False),
    sa.Column('tipo_dato_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cultivo_plaga_id'], ['cultivo_plaga.id'], ),
    sa.ForeignKeyConstraint(['tipo_dato_id'], ['tipo_dato.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('metadatos', schema=None) as batch_op:
        batch_op.alter_column('valor',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('fuente',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('fecha_creacion',
               existing_type=mysql.DATETIME(),
               nullable=True)

    with op.batch_alter_table('plagas', schema=None) as batch_op:
        batch_op.alter_column('public_id',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('agente_causante',
               existing_type=mysql.VARCHAR(length=300),
               type_=sa.String(length=100),
               nullable=False)

    with op.batch_alter_table('predicciones', schema=None) as batch_op:
        batch_op.alter_column('tendencia_temp_max',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('tendencia_temp_min',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predicciones', schema=None) as batch_op:
        batch_op.alter_column('tendencia_temp_min',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('tendencia_temp_max',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('plagas', schema=None) as batch_op:
        batch_op.alter_column('agente_causante',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=300),
               nullable=True)
        batch_op.alter_column('public_id',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)

    with op.batch_alter_table('metadatos', schema=None) as batch_op:
        batch_op.alter_column('fecha_creacion',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('fuente',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('valor',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)

    op.drop_table('cultivo_plaga_requisito')
    op.drop_table('tipo_dato')
    # ### end Alembic commands ###
