"""new column for plagues. Now you can register the algorithm url if u want to use and external one to make predictions

Revision ID: 66ab16e8c6c8
Revises: d3158d2685fd
Create Date: 2026-04-24 08:48:02.455507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66ab16e8c6c8'
down_revision = 'd3158d2685fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plagas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('algoritmo_url', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plagas', schema=None) as batch_op:
        batch_op.drop_column('algoritmo_url')

    # ### end Alembic commands ###
