"""added nullables in required mediciones_climaticas fields 2

Revision ID: 9161555d1531
Revises: cd90be82fe7a
Create Date: 2026-05-25 14:47:46.419542

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9161555d1531'
down_revision = 'cd90be82fe7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dispositivos', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('mediciones_climaticas', schema=None) as batch_op:
        batch_op.alter_column('temperatura',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('precipitacion',
               existing_type=mysql.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mediciones_climaticas', schema=None) as batch_op:
        batch_op.alter_column('precipitacion',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('temperatura',
               existing_type=mysql.FLOAT(),
               nullable=False)

    with op.batch_alter_table('dispositivos', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
