"""fix changed unique constraint in mediciones_sensor table

Revision ID: b521ed94a494
Revises: f61b3a0d5280
Create Date: 2026-05-26 16:49:29.741207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b521ed94a494'
down_revision = 'f61b3a0d5280'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('mediciones_sensor', schema=None) as batch_op:
        batch_op.drop_constraint('mediciones_sensor_ibfk_1', type_='foreignkey')
        batch_op.drop_index('uq_sensor_data')
        batch_op.create_unique_constraint('uq_sensor_data', ['sensor_id', 'timestamp', 'campo'])
        batch_op.create_foreign_key(
            'mediciones_sensor_ibfk_1',
            'sensores',
            ['sensor_id'], ['id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mediciones_sensor', schema=None) as batch_op:
        batch_op.drop_constraint('uq_sensor_data', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_sensor_data'), ['sensor_id', 'timestamp'])

    # ### end Alembic commands ###
