"""new column for plagues. Now you can register the algorithm to process in predictor

Revision ID: d3158d2685fd
Revises: 2262aaf397dd
Create Date: 2026-04-23 19:05:03.673095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3158d2685fd'
down_revision = '2262aaf397dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plagas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('algoritmo', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plagas', schema=None) as batch_op:
        batch_op.drop_column('algoritmo')

    # ### end Alembic commands ###
