"""new temporal-window field for predictors

Revision ID: d6a14d2355b3
Revises: efd35c3c88fc
Create Date: 2026-04-21 08:35:50.548100

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd6a14d2355b3'
down_revision = 'efd35c3c88fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plagas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ventana_temporal', sa.JSON(), nullable=True))
        batch_op.alter_column('condiciones_evaluables',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plagas', schema=None) as batch_op:
        batch_op.alter_column('condiciones_evaluables',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               nullable=True)
        batch_op.drop_column('ventana_temporal')

    # ### end Alembic commands ###
