"""fix dispositivos id column

Revision ID: db4e2a62b5dd
Revises: 9161555d1531
Create Date: 2026-05-25 14:54:28.201721

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'db4e2a62b5dd'
down_revision = '9161555d1531'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dispositivos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('dev_eui'))

    with op.batch_alter_table('mediciones_climaticas', schema=None) as batch_op:
        batch_op.alter_column('temperatura',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('precipitacion',
               existing_type=mysql.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mediciones_climaticas', schema=None) as batch_op:
        batch_op.alter_column('precipitacion',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('temperatura',
               existing_type=mysql.FLOAT(),
               nullable=False)

    with op.batch_alter_table('dispositivos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('dev_eui'), ['dev_eui'], unique=True)

    # ### end Alembic commands ###
