"""added new required file to ingesta_status

Revision ID: de30876c8ac1
Revises: 99bfd00b54c4
Create Date: 2026-05-21 17:01:09.916594

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'de30876c8ac1'
down_revision = '99bfd00b54c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('ingesta_status', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_ingesta_dataset_fecha', ['dataset', 'tipo', 'year', 'month', 'day', 'zona', 'codigo'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingesta_status', schema=None) as batch_op:
        batch_op.drop_constraint('uq_ingesta_dataset_fecha', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_ingesta_dataset_fecha'), ['dataset', 'tipo', 'year', 'month', 'day', 'zona'])
        batch_op.drop_column('codigo')

    op.execute('ALTER TABLE dispositivos MODIFY id INTEGER(11) NOT NULL AUTO_INCREMENT PRIMARY KEY')
