"""new plague field for predictors

Revision ID: efd35c3c88fc
Revises: 237f001c7e87
Create Date: 2026-04-15 12:58:30.129505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efd35c3c88fc'
down_revision = '237f001c7e87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plagas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('condiciones_evaluables', sa.JSON(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plagas', schema=None) as batch_op:
        batch_op.drop_column('condiciones_evaluables')

    # ### end Alembic commands ###
