"""fix changed mediciones_sensor's columns

Revision ID: f61b3a0d5280
Revises: db4e2a62b5dd
Create Date: 2026-05-26 11:19:17.274711

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f61b3a0d5280'
down_revision = 'db4e2a62b5dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mediciones_sensor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('campo', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('valor', sa.Float(), nullable=True))
        batch_op.drop_column('humedad_suelo')
        batch_op.drop_column('temperatura_hojas')
        batch_op.drop_column('temperatura_maxima')
        batch_op.drop_column('temperatura_DS18B20')
        batch_op.drop_column('humedad_foliar')
        batch_op.drop_column('temperatura_minima')
        batch_op.drop_column('temperatura_suelo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mediciones_sensor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temperatura_suelo', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('temperatura_minima', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('humedad_foliar', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('temperatura_DS18B20', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('temperatura_maxima', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('temperatura_hojas', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('humedad_suelo', mysql.FLOAT(), nullable=True))
        batch_op.drop_column('valor')
        batch_op.drop_column('campo')

    # ### end Alembic commands ###
